name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-dep

      - name: Build Project (if applicable)
        run: npm run build # Adjust based on your project
        
      - name: Authenticate Firebase
        run: firebase login:ci --no-localhost --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase
        run: firebase deploy --only hosting:flight-v2 --project flight-details-b4fd2 --token "${{ secrets.FIREBASE_TOKEN }}"
